### PR TITLE
Refactor project and make routes work

### PR DESCRIPTION
**Pull request by tok3rat0r**
Project refactored to be more in line with Flask best practices, and routes are now accessible without 404 errors.

### CODE REVIEW

**Comment by Anzigar** [comment]
I got another problem

**Comment by Anzigar** [comment]
env) apple@ansi journeybackend-main % flask run
Traceback (most recent call last):
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/flask/cli.py", line 1050, in main
    cli.main()
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/flask/cli.py", line 911, in run_command
    raise e from None
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/flask/cli.py", line 897, in run_command
    app = info.load_app()
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/flask/cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/Users/ansi/Downloads/journeybackend-main/app.py", line 4, in <module>
    from item import ma
  File "/Users/ansi/Downloads/journeybackend-main/item.py", line 7, in <module>
    class UserSchema(ma.SQLAlchemyAutoSchema):
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/marshmallow/schema.py", line 121, in __new__
    klass._declared_fields = mcs.get_declared_fields(
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/marshmallow_sqlalchemy/schema.py", line 91, in get_declared_fields
    fields.update(mcs.get_declared_sqla_fields(fields, converter, opts, dict_cls))
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/marshmallow_sqlalchemy/schema.py", line 130, in get_declared_sqla_fields
    converter.fields_for_model(
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/marshmallow_sqlalchemy/convert.py", line 154, in fields_for_model
    field = base_fields.get(key) or self.property2field(prop)
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/marshmallow_sqlalchemy/convert.py", line 193, in property2field
    field_class = field_class or self._get_field_class_for_property(prop)
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/marshmallow_sqlalchemy/convert.py", line 275, in _get_field_class_for_property
    column = _base_column(prop.columns[0])
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 1329, in __getattr__
    return self._fallback_getattr(key)
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 1298, in _fallback_getattr
    raise AttributeError(key)
AttributeError: columns
(env) apple@ansi journeybackend-main % flask run
Traceback (most recent call last):
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/flask/cli.py", line 1050, in main
    cli.main()
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/flask/cli.py", line 911, in run_command
    raise e from None
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/flask/cli.py", line 897, in run_command
    app = info.load_app()
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/flask/cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/Users/ansi/Downloads/journeybackend-main/app.py", line 4, in <module>
    from item import ma
  File "/Users/ansi/Downloads/journeybackend-main/item.py", line 7, in <module>
    class UserSchema(ma.SQLAlchemyAutoSchema):
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/marshmallow/schema.py", line 121, in __new__
    klass._declared_fields = mcs.get_declared_fields(
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/marshmallow_sqlalchemy/schema.py", line 91, in get_declared_fields
    fields.update(mcs.get_declared_sqla_fields(fields, converter, opts, dict_cls))
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/marshmallow_sqlalchemy/schema.py", line 130, in get_declared_sqla_fields
    converter.fields_for_model(
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/marshmallow_sqlalchemy/convert.py", line 154, in fields_for_model
    field = base_fields.get(key) or self.property2field(prop)
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/marshmallow_sqlalchemy/convert.py", line 193, in property2field
    field_class = field_class or self._get_field_class_for_property(prop)
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/marshmallow_sqlalchemy/convert.py", line 275, in _get_field_class_for_property
    column = _base_column(prop.columns[0])
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 1329, in __getattr__
    return self._fallback_getattr(key)
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 1298, in _fallback_getattr
    raise AttributeError(key)
AttributeError: columns

**Comment by tok3rat0r** [comment]
Can't help you with that, it's dependent on your system and the setup of your virtual env. I built and ran with Docker, which worked fine.

**Comment by Anzigar** [comment]
Ok, thanks.

**Pull request merged**
